version: '3.7'

services:
 frontend:
    build: ./src/front-end
    container_name: frontend
    restart: on-failure
    environment:
      SERVER_HOST : ${SERVER_HOST}
      SERVER_PORT : ${SERVER_PORT}
      DB_HOST : ${DB_HOST}
      DB_PORT : ${DB_PORT}
      DB_USERNMAE : ${DB_USERNMAE}
      DB_PASSWORD : ${DB_PASSWORD}
      DB_DATABASE : ${DB_DATABASE}
      CLIENT_ID : ${CLIENT_ID}
      TOKEN_SECRET : ${TOKEN_SECRET}
      CLIENT_SECRET : ${CLIENT_SECRET}
      CALLBACK_URL : ${CALLBACK_URL}
      VITE_HOST : ${VITE_HOST}
      VITE_SERVER_PORT : ${VITE_SERVER_PORT}
      VITE_APP_PORT : ${VITE_APP_PORT}
      VITE_API : ${VITE_API}
      POSTGRESQL_PASS : ${POSTGRESQL_PASS}
      DB_NAME : ${DB_NAME}
      PMA_HOST : ${PMA_HOST}
      PMA_PORT : ${PMA_PORT}
    init : true
    networks:
    - my_network
    ports:
      - "5000:5000"
 backend:
    build: ./src/backend
    container_name: backend
    restart: on-failure
    environment:
      SERVER_HOST : ${SERVER_HOST}
      SERVER_PORT : ${SERVER_PORT}
      DB_HOST : ${DB_HOST}
      DB_PORT : ${DB_PORT}
      DB_USERNMAE : ${DB_USERNMAE}
      DB_PASSWORD : ${DB_PASSWORD}
      DB_DATABASE : ${DB_DATABASE}
      CLIENT_ID : ${CLIENT_ID}
      TOKEN_SECRET : ${TOKEN_SECRET}
      CLIENT_SECRET : ${CLIENT_SECRET}
      CALLBACK_URL : ${CALLBACK_URL}
      VITE_HOST : ${VITE_HOST}
      VITE_SERVER_PORT : ${VITE_SERVER_PORT}
      VITE_APP_PORT : ${VITE_APP_PORT}
      VITE_API : ${VITE_API}
      POSTGRESQL_PASS : ${POSTGRESQL_PASS}
      DB_NAME : ${DB_NAME}
      PMA_HOST : ${PMA_HOST}
      PMA_PORT : ${PMA_PORT}
    init : true
    networks:
    - my_network
    ports:
      - "3000:3000"
 postgresql:
    build: ./src/postgresql
    container_name: postgresql
    restart: on-failure
    environment:
      POSTGRESQL_PASS : ${POSTGRESQL_PASS}
      DB_NAME : ${DB_NAME}
      PMA_HOST : ${PMA_HOST}
      PMA_PORT : ${PMA_PORT}
      PGADMIN_DEFAULT_EMAIL : ${PGADMIN_DEFAULT_EMAIL}
      PGADMIN_DEFAULT_PASSWORD : ${PGADMIN_DEFAULT_PASSWORD}
    init : true
    networks:
      - my_network
    ports:
      - "5432:5432"
 pgadmin:
  image: dpage/pgadmin4
  restart: always
  env_file:
    - .env
  ports:
    - "5050:80"
  networks:
    - my_network

networks:
  my_network:
    driver: bridge
