# POST http://localhost:3000/users HTTP/1.1
# content-type: application/json

# {
#     "id": 8512,
#     "username": "wdwdw",
#     "password": "heldwdwdwloWorld",
#     "avatar": "dwdwdwd",
#     "wins": 2,
#     "loss": 4433,
#     "winrate": 22100
# }

GET http://localhost:3000/users HTTP/1.1
content-type: application/json