export { default as Profile } from './Profile/Profile'
export { default as Navbar } from './Navbar/Navbar'
export { default as HomePage } from './HomePage/HomePage'
export { default as SignIn} from './HomePage/SignIn'
export { default as LoadingPage} from './HomePage/LoadingPage'
export { default as MainPage} from './HomePage/MainPage'
export { default as MainWrapper} from './HomePage/MainWrapper'
export { default as TwoFactor} from './HomePage/TwoFactor'
export { default as Chat } from './Chat/Chat'
export { default as Channels } from './Chat/Channels' 
export { default as LeaderBoard } from './HomePage/LeaderBoard'
export { default as ResultsLatestHome } from './HomePage/ResultsMatch'
export { default as LiveMatches} from './HomePage/liveMatches'
