export { default as Profile } from './Profile/Profile'
export { default as Navbar } from './Navbar/Navbar'
export { default as HomePage } from './HomePage/HomePage'
export { default as SignIn} from './signIn'
export { default as Chat } from './Chat/Chat'
export { default as Channels } from './Chat/Channels' 
export { default as LeaderBoard } from './HomePage/LeaderBoard'
export { default as ResultsLatestHome } from './HomePage/ResultsMatch'
export {default as LiveMatches} from './HomePage/liveMatches'